name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Compile to EXE
        run: |
          mkdir -Force dist
        
          echo '{"pkg": {"assets": ["README.md"]}}' > pkg-config.json
          
          pnpm dlx @yao-pkg/pkg twitch-dlp.js `
            --targets node24-win-x64 `
            --config pkg-config.json `
            --output dist/twitch-dlp.exe
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twitch-dlp-win
          path: dist/twitch-dlp.exe
